version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
      - POSTGRES_DB = postgres
    restart : always
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - pgnetwork

  server:
    build: .
    ports:
      - '6969:6969'
    networks :
      - pgnetwork
    restart : always
    expose:
      - '5432'
    depends_on:
      - db
    volumes:
      - local_db_backup:/app
    links : 
      - db

volumes:
  db:
    driver: local
  local_db_backup:

networks:
  pgnetwork:
    driver: bridge