version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data_for_task3
    networks:
      - pgnetwork

  server:
    build: .
    ports:
      - '6969:6969'
    networks :
      - pgnetwork
    restart : always
    depends_on:
      - db
    volumes:
      - urmom:/app
    links : 
      - db
    

  
volumes:
  db:
    driver: local
  urmom:

networks:
  pgnetwork:
    driver: bridge